### ISSUE TITLE
python3.6和以上版本无法安装Pillow3.4.1

### ISSUE THREAD

**Issue by PalAlexx** [palxex/palresearch#5]
建议将Pillow版本升级至5.2-5.4 或者6.x
因为这两者可同时支持Python2.7和python3.4-3.7

https://pillow.readthedocs.io/en/stable/installation.html

**Comment by palxex** [comment]
Will do it later; current showstopper is palette quantizing, using a hacky way that only works on pillow 3.4.x.

**Comment by palxex** [comment]
Up to date now.
