### ISSUE TITLE
新人问下，如何编辑敌我数值，文档很多，但我还没头绪

### ISSUE THREAD

**Issue by guotong1988** [palxex/palresearch#7]
感谢！
从编辑敌我数值入门吧，
感谢！

**Comment by palxex** [comment]
已在sdlpal gitter回复。
这里的文档颇有些层累，可能不太易读，多讨论就是:)

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/72768921-e4eda680-3c33-11ea-8a89-86e99d684bd7.png)
THX
