### ISSUE TITLE
有没有MOD制作交流群？

### ISSUE THREAD

**Issue by guotong1988** [palxex/palresearch#8]
谢谢！

**Comment by palxex** [comment]
这个还真不清楚，没怎么参与过，可能在百度贴吧问问看比较合适- -
仙剑的脚本设计（正交度相当有限，更别提图灵完备了）决定了它并不是特别适合做大型mod（金庸那种），想作任何功能延伸基本都要增补脚本指令集，而仙剑社区又没有像金庸社区一样早早形成用第三方脚本扩展的习惯，这造成了大型mod基本都会同时改代码（增设自己专用的脚本指令、修改战斗实现等），而跨平台实现（比如sdlpal）基本只能选择支持离原设不是太远的mod的怪现状，可见的未来估计也不会有什么改变。palresearch基于解析原作、为其他实现提供理论支持的立场，对mod的考虑有限，比如没有收入任何（不管用的有多广）mod扩展的脚本指令（未来也不太可能，因为扩展指令需要赋指令号，而指令号空间同一，导致多数不同的mod基本都为自己的扩展指令赋了同样的号……）

**Comment by DaBaiTuu** [comment]
其实建议不妨收录梦幻Mod，作为 经典流传的Mod也足以有深远影响了
